apiVersion: apps/v1

kind: Deployment

metadata:
    name: test-deployment

spec:
    replicas: 2

    # selector's matchLabel can have any key and any value
    selector:
        matchLabels:
            selectorLabelValue: deployment-rs-pod

    template:
        metadata:
            name: testDeploymentRsPod01
            labels:
                selectorLabelValue: deployment-rs-pod
        spec:
            containers:
                - name: c01
                  image: ubuntu
                  command: ["/bin/bash", "-c", "while true; do echo 'I am container c01'; sleep 5; done"]
                  env:
                      - name: FIRST_NAME
                        value: Lokesh
                      - name: LAST_NAME
                        value: Mittal
